In [1]:
#Q2. Row Echelon Form:
#Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9.
#To generate the random matrix, set the random seed as the last two digits of your roll number.
#Reduce matrix A to its Row Echelon Form by performing elementary row operations

In [2]:
import numpy as np

# Set the random seed based on the last two digits of your roll number
roll_number_last_two_digits = 22  # Change this to your last two digits
np.random.seed(22)


In [3]:
# Generate a 5x5 matrix A with random entries between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))
print("Matrix A:")
print(A)

Matrix A:
[[5 4 0 4 6]
 [6 4 8 4 2]
 [8 7 2 9 8]
 [8 5 4 2 2]
 [1 6 9 3 3]]


In [4]:
# Function to perform elementary row operations to reduce matrix to row echelon form
def row_echelon_form(matrix):
    lead = 0
    rowCount = len(matrix)
    columnCount = len(matrix[0])
    for r in range(rowCount):
        if lead >= columnCount:
            return
        i = r
        while matrix[i][lead] == 0:
            i += 1
            if i == rowCount:
                i = r
                lead += 1
                if columnCount == lead:
                    return
        matrix[i], matrix[r] = matrix[r], matrix[i]
        lv = matrix[r][lead]
        matrix[r] = [mrx / float(lv) for mrx in matrix[r]]
        for i in range(rowCount):
            if i != r:
                lv = matrix[i][lead]
                matrix[i] = [iv - lv*rv for rv, iv in zip(matrix[r], matrix[i])]
        lead += 1


In [5]:
# Reduce matrix A to row echelon form
row_echelon_form(A)
print("\nRow Echelon Form of Matrix A:")
print(A)



Row Echelon Form of Matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
